image: gradle:aphine
stages:
 - build
 - test
 - deploy
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GET_STRATEGY: clone 

before_script:
    - chmod +x ./gradlew
    - export GRADLE_USER_HOME='pwd'/.gradle
    
build:
  stage: build
  script: ./gradlew --build-cache assemble
  tags:
    - grad

test:
  stage: test
  script: ./gradlew check
  tags:
    - grad
    
deploy_stagging:
    stage: deploy
    tags:
      - dalfcs_gitlab_docker_ci
    image: ruby:2.6
    script:
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl
      - dpl --provider=heroku --app=$Heroku_APP_Name --api-key=$Heroku_API_KEY
    only:
      - develop
deploy_production:
    stage: deploy
    tags:
      - dalfcs_gitlab_docker_ci
    image: ruby:2.6
    script:
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl
      - dpl --provider=heroku --app=$Heroku_APP_Name_production --api-key=$Heroku_API_KEY
    only:
      - master